spring.application.name=rmstudiofitness

# === PostgreSQL ===
# (Sugestão: use env vars; cai no default se não tiver)
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/rmstudio}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASS:postgres}

# Pool (ajusta conforme sua máquina)
spring.datasource.hikari.maximum-pool-size=10

# === JPA / Hibernate ===
spring.jpa.hibernate.ddl-auto=update         
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# Evita queries na renderização de view (boa prática)
spring.jpa.open-in-view=false

# (Opcional) timezone consistente p/ datas
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# === Logs úteis em dev (ver SQL + parâmetros) ===
logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.orm.jdbc.bind=trace

# === Thymeleaf ===
# Se você NÃO vai usar Thymeleaf, remova a dependência do pom.
# Se quiser só silenciar o aviso de templates ausentes:
spring.thymeleaf.check-template-location=false